before:
  hooks:
    - go mod download
    - rm -rf dist
builds:
  - env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    goos:
      - linux
      - windows
    goarch:
      - amd64
archives:
  - replacements:
      amd64: x86_64
checksum:
  name_template: "checksums.txt"
