language: go

go:
  - 1.12.x

os:
  - linux

cache:
  directories:
    - "$HOME/.cache/go-build"
    - "$HOME/gopath/pkg/mod"

env:
  - GO111MODULE=on

branches:
  only:
    - master

git:
  depth: 1

install: true

deploy:
  provider: releases
  api_key:
    secure: $GITHUB_OAUTH_TOKEN
  file:
    - prun.exe
    - prun
  skip_cleanup: true
  on:
    tags: true
